### ISSUE TITLE
Support for TMC2130 Silent StepStick

### ISSUE THREAD

**Issue by jrsphoto** [jbrazio/ardufocus#4]
I've downloaded your code and I'm trying to figure out how I might go about adding support for the TCM2130 Silent Stepstick drivers. I've got a few from other projects and they have some very nice features that I think would be nice for use in a focuser.  They are complicated drivers but there are some nice Arduino libraries available, this one I've used in the past:

https://github.com/teemuatlut/TMC2130Stepper

Got any pointers as to how I would I go about adding this library, and support for its functions, to your ardufocus program

**Comment by jbrazio** [comment]
Hi @jrsphoto ! This is something that already crossed my mind, specially because by using TCM2130 we would gain "free" endstops. My code is not 100% Arduino environment compatible, have you tried to include the libs ? At least you would need to create a new wrapper object to handle the specificities of TCM2130. I would suggest to have a look at [a4988.cpp](https://github.com/jbrazio/ardufocus/blob/master/ardufocus/a4988.cpp) and [a4988.h](https://github.com/jbrazio/ardufocus/blob/master/ardufocus/a4988.h).
